import { useState } from "react";
import { ArrowRight, X } from "lucide-react";

const BRAND_RED = "#9c1a35";

const slides = [
  {
    // Real photo — kept as a live image with real text overlaid on top,
    // never baked/regenerated by AI, so her likeness is never altered.
    isLiveHero: true,
    image: "/images/coylah.jpg",
    signature: "Love Coylah",
    title: "Welcome to\nThe Collagen Kitchen",
    description: "Real food. Real glow.\nBuilt around your skin.",
    cta: "Start",
  },
  { image: "/images/onboarding-2-fuels-skin.jpg", cta: "Next" },
  { image: "/images/onboarding-3-everything.jpg", cta: "Next" },
  { image: "/images/onboarding-4-glow-bowl.jpg", cta: "Next" },
  { image: "/images/onboarding-5-home-screen.jpg", cta: "I'm ready!" },
];

export default function WelcomeModal({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState(0);
  const slide = slides[step];

  const next = () => {
    if (step === slides.length - 1) {
      onClose();
    } else {
      setStep(step + 1);
    }
  };

  const back = () => setStep(step - 1);
  const skip = () => onClose();

  return (
    <div className="fixed inset-0 bg-white z-50 flex flex-col overflow-hidden">
      {/* Top bar: dots + close */}
      <div className="flex items-center justify-between px-5 pt-4 pb-2 shrink-0">
        <div className="w-6" />
        <div className="flex gap-1.5">
          {slides.map((_, i) => (
            <div
              key={i}
              className="h-1.5 rounded-full transition-all"
              style={{
                width: i === step ? "20px" : "6px",
                backgroundColor: i === step ? BRAND_RED : "#e5e7eb",
              }}
            />
          ))}
        </div>
        <button
          onClick={onClose}
          className="w-6 h-6 flex items-center justify-center text-gray-400"
        >
          <X size={18} />
        </button>
      </div>

      {slide.isLiveHero ? (
        <>
          {/* Real photo, real text — nothing AI-altered */}
          <div
            className="shrink-0 relative overflow-hidden bg-white flex items-center justify-center"
            style={{ height: "clamp(300px, 50vh, 460px)" }}
          >
            <img
              src={slide.image}
              className="w-full h-full object-cover"
              style={{ objectPosition: "center 15%" }}
            />
            <div
              className="absolute bottom-0 left-0 right-0 h-20 pointer-events-none"
              style={{ background: "linear-gradient(to bottom, transparent, white)" }}
            />
          </div>
          <div className="shrink-0 px-6 pt-3 text-center">
            <p className="font-serif italic text-base mb-0.5" style={{ color: BRAND_RED }}>
              {slide.signature}
            </p>
            <h2 className="text-xl font-serif leading-tight whitespace-pre-line mb-2">
              {slide.title}
            </h2>
            <div className="w-7 h-[2px] mx-auto mb-2" style={{ backgroundColor: BRAND_RED }} />
            <p className="text-gray-500 text-[13px] leading-snug whitespace-pre-line max-w-xs mx-auto">
              {slide.description}
            </p>
          </div>
          <div className="flex-1 min-h-4" />
        </>
      ) : (
        /* Baked mockup artwork for the remaining slides (no faces involved) */
        <div className="flex-1 min-h-0 flex items-center justify-center px-4">
          <img
            src={slide.image}
            className="max-w-full max-h-full w-auto h-auto object-contain"
          />
        </div>
      )}

      {/* Fixed footer */}
      <div className="px-6 pb-6 pt-2 space-y-1.5 shrink-0">
        {step > 0 && (
          <button
            onClick={back}
            className="w-full border border-gray-300 rounded-xl py-2.5 text-gray-500 text-sm"
          >
            Back
          </button>
        )}

        <button
          onClick={next}
          className="w-full text-white rounded-xl py-3 text-sm font-medium flex items-center justify-center gap-2"
          style={{ backgroundColor: BRAND_RED }}
        >
          {slide.cta}
          <ArrowRight size={15} />
        </button>

        <button onClick={skip} className="w-full text-[11px] text-gray-400 pt-0.5">
          Skip
        </button>
      </div>
    </div>
  );
}
