/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as BuildYoghurtBowlRouteImport } from './routes/build.yoghurt-bowl'
import { Route as BuildGlowBowlRouteImport } from './routes/build.glow-bowl'
import { Route as AdminImportRouteImport } from './routes/admin.import'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildYoghurtBowlRoute = BuildYoghurtBowlRouteImport.update({
  id: '/build/yoghurt-bowl',
  path: '/build/yoghurt-bowl',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildGlowBowlRoute = BuildGlowBowlRouteImport.update({
  id: '/build/glow-bowl',
  path: '/build/glow-bowl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/planner': typeof PlannerRoute
  '/shopping': typeof ShoppingRoute
  '/admin/import': typeof AdminImportRoute
  '/build/glow-bowl': typeof BuildGlowBowlRoute
  '/build/yoghurt-bowl': typeof BuildYoghurtBowlRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/planner': typeof PlannerRoute
  '/shopping': typeof ShoppingRoute
  '/admin/import': typeof AdminImportRoute
  '/build/glow-bowl': typeof BuildGlowBowlRoute
  '/build/yoghurt-bowl': typeof BuildYoghurtBowlRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/planner': typeof PlannerRoute
  '/shopping': typeof ShoppingRoute
  '/admin/import': typeof AdminImportRoute
  '/build/glow-bowl': typeof BuildGlowBowlRoute
  '/build/yoghurt-bowl': typeof BuildYoghurtBowlRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favourites'
    | '/planner'
    | '/shopping'
    | '/admin/import'
    | '/build/glow-bowl'
    | '/build/yoghurt-bowl'
    | '/recipes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favourites'
    | '/planner'
    | '/shopping'
    | '/admin/import'
    | '/build/glow-bowl'
    | '/build/yoghurt-bowl'
    | '/recipes/$slug'
  id:
    | '__root__'
    | '/'
    | '/favourites'
    | '/planner'
    | '/shopping'
    | '/admin/import'
    | '/build/glow-bowl'
    | '/build/yoghurt-bowl'
    | '/recipes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesRoute: typeof FavouritesRoute
  PlannerRoute: typeof PlannerRoute
  ShoppingRoute: typeof ShoppingRoute
  AdminImportRoute: typeof AdminImportRoute
  BuildGlowBowlRoute: typeof BuildGlowBowlRoute
  BuildYoghurtBowlRoute: typeof BuildYoghurtBowlRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/yoghurt-bowl': {
      id: '/build/yoghurt-bowl'
      path: '/build/yoghurt-bowl'
      fullPath: '/build/yoghurt-bowl'
      preLoaderRoute: typeof BuildYoghurtBowlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/glow-bowl': {
      id: '/build/glow-bowl'
      path: '/build/glow-bowl'
      fullPath: '/build/glow-bowl'
      preLoaderRoute: typeof BuildGlowBowlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesRoute: FavouritesRoute,
  PlannerRoute: PlannerRoute,
  ShoppingRoute: ShoppingRoute,
  AdminImportRoute: AdminImportRoute,
  BuildGlowBowlRoute: BuildGlowBowlRoute,
  BuildYoghurtBowlRoute: BuildYoghurtBowlRoute,
  RecipesSlugRoute: RecipesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
