/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyThisWorksRouteImport } from './routes/why-this-works'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as BoneBrothRouteImport } from './routes/bone-broth'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as BuildYoghurtBowlRouteImport } from './routes/build.yoghurt-bowl'
import { Route as BuildGlowBowlRouteImport } from './routes/build.glow-bowl'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'

const WhyThisWorksRoute = WhyThisWorksRouteImport.update({
  id: '/why-this-works',
  path: '/why-this-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const BoneBrothRoute = BoneBrothRouteImport.update({
  id: '/bone-broth',
  path: '/bone-broth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildYoghurtBowlRoute = BuildYoghurtBowlRouteImport.update({
  id: '/build/yoghurt-bowl',
  path: '/build/yoghurt-bowl',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildGlowBowlRoute = BuildGlowBowlRouteImport.update({
  id: '/build/glow-bowl',
  path: '/build/glow-bowl',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bone-broth': typeof BoneBrothRoute
  '/favourites': typeof FavouritesRoute
  '/planner': typeof PlannerRoute
  '/shopping': typeof ShoppingRoute
  '/why-this-works': typeof WhyThisWorksRoute
  '/build/glow-bowl': typeof BuildGlowBowlRoute
  '/build/yoghurt-bowl': typeof BuildYoghurtBowlRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bone-broth': typeof BoneBrothRoute
  '/favourites': typeof FavouritesRoute
  '/planner': typeof PlannerRoute
  '/shopping': typeof ShoppingRoute
  '/why-this-works': typeof WhyThisWorksRoute
  '/build/glow-bowl': typeof BuildGlowBowlRoute
  '/build/yoghurt-bowl': typeof BuildYoghurtBowlRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bone-broth': typeof BoneBrothRoute
  '/favourites': typeof FavouritesRoute
  '/planner': typeof PlannerRoute
  '/shopping': typeof ShoppingRoute
  '/why-this-works': typeof WhyThisWorksRoute
  '/build/glow-bowl': typeof BuildGlowBowlRoute
  '/build/yoghurt-bowl': typeof BuildYoghurtBowlRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bone-broth'
    | '/favourites'
    | '/planner'
    | '/shopping'
    | '/why-this-works'
    | '/build/glow-bowl'
    | '/build/yoghurt-bowl'
    | '/recipes/$slug'
    | '/admin/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bone-broth'
    | '/favourites'
    | '/planner'
    | '/shopping'
    | '/why-this-works'
    | '/build/glow-bowl'
    | '/build/yoghurt-bowl'
    | '/recipes/$slug'
    | '/admin/import'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bone-broth'
    | '/favourites'
    | '/planner'
    | '/shopping'
    | '/why-this-works'
    | '/build/glow-bowl'
    | '/build/yoghurt-bowl'
    | '/recipes/$slug'
    | '/_authenticated/admin/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BoneBrothRoute: typeof BoneBrothRoute
  FavouritesRoute: typeof FavouritesRoute
  PlannerRoute: typeof PlannerRoute
  ShoppingRoute: typeof ShoppingRoute
  WhyThisWorksRoute: typeof WhyThisWorksRoute
  BuildGlowBowlRoute: typeof BuildGlowBowlRoute
  BuildYoghurtBowlRoute: typeof BuildYoghurtBowlRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-this-works': {
      id: '/why-this-works'
      path: '/why-this-works'
      fullPath: '/why-this-works'
      preLoaderRoute: typeof WhyThisWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bone-broth': {
      id: '/bone-broth'
      path: '/bone-broth'
      fullPath: '/bone-broth'
      preLoaderRoute: typeof BoneBrothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/yoghurt-bowl': {
      id: '/build/yoghurt-bowl'
      path: '/build/yoghurt-bowl'
      fullPath: '/build/yoghurt-bowl'
      preLoaderRoute: typeof BuildYoghurtBowlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/glow-bowl': {
      id: '/build/glow-bowl'
      path: '/build/glow-bowl'
      fullPath: '/build/glow-bowl'
      preLoaderRoute: typeof BuildGlowBowlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BoneBrothRoute: BoneBrothRoute,
  FavouritesRoute: FavouritesRoute,
  PlannerRoute: PlannerRoute,
  ShoppingRoute: ShoppingRoute,
  WhyThisWorksRoute: WhyThisWorksRoute,
  BuildGlowBowlRoute: BuildGlowBowlRoute,
  BuildYoghurtBowlRoute: BuildYoghurtBowlRoute,
  RecipesSlugRoute: RecipesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
